---
title: "Case Study 1"
members: "Senthil Kumar", "Sabrina Purvis", "Akbar Thobani"
date: "2/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Finding Breweries count by State

#Data clean and heat map for Breweries Data 
#Data has been read into a Dataframe called "BrewData"

library(tidyverse)
library(ggplot2)
library(maps)
library(dplyr)
library(mapproj)
library(naniar)


#Read Data into Variables
BrewData <- read.csv(file.choose(),header = TRUE)
BeerData <- read.csv(file.choose(),header = TRUE)

#Rename Beers Name column
colnames(BeerData)[1]="Beer_Name"

#Rename Breweries Name column
colnames(BrewData)[2]="Brewery_Name"

#Check the data

str(BrewData)
head(BrewData)

str(BeerData)
head(BeerData)

#Rename Brewery_id column name in Beers data to "Brew_ID". This will ensure the joining key column names are the same for Merging the data.

colnames(BeerData)[5]="Brew_ID"

#Trim the leading whitespace from the "State" column variables in Breweries data. This is necessary for Merging the data with map data which has the joining key column as State.

BrewData$State <- trimws(BrewData$State)

# Questions that we find the answers for 
####################################################
## 1. How many breweries are present in each state?
####################################################

#make a data frame with State name and abbreviation(abb). 
lookup = data.frame(abb = state.abb, State = state.name) 

str(lookup)
head(lookup)

#Change the state Column Name in Breweries Data to "abb". This step is required for merging this dataset with the map data that has the joining key column as abb.

colnames(BrewData)[4]="abb"

#Select only the column data that is needed for the Analysis and store in a data frame
Brew=BrewData %>% select(Brewery_Name,abb) %>% group_by(abb)
#Breweries %>% select (Name,State) %>% group_by(State) %>% summarize(count=n())

# Merge the Brewery dataset with lookup map data
Brew2 = merge(Brew,lookup,"abb")

#count up the occurance of each state.
BrewMapData=count(Brew2,State)

#Change column name "n" for the count to be more meaningful
colnames(BrewMapData)[2]="Breweries_Count"

#Add a region column with lower case to main dataset and delete the duplicate State column
#This would be used for Merging with mapping data 
BrewMapData$region <- tolower(BrewMapData$State)
BrewMapData2=BrewMapData[-1]
states <- map_data("state")

# Merge the Breweries Data with the mapping data for heat map
map.df <- merge(states,BrewMapData2, by="region", all.x=T)
map.df <- map.df[order(map.df$order),]

#Plot the dataset to visualize the heatmap of Breweries count by State.
ggplot(map.df, aes(x=long,y=lat,group=group))+
  geom_polygon(aes(fill=Breweries_Count))+
  geom_path()+ 
  scale_fill_gradientn(colours=rev(heat.colors(10)),na.value="grey10")+ggtitle("Breweries Count by State")+
coord_map()


#########################################################################################
# 2. Merge beer data with the breweries data. 
# Print the first 6 observations and the last six observations to check the merged file
##########################################################################################

#Merge Beer with Breweries by performing an inner join
BeerMerge1=merge(BeerData,BrewData,"Brew_ID")

#Rename the column name "abb" back to "State". 
#We renamed the state column when we merged the Breweries dataset with the map data.

colnames(BeerMerge1)[10]="State"

#Print the first 6 rows and last 6 rows of Merged data
head(BeerMerge1)
tail(BeerMerge1)


############################################
# 3. Address missing values in each column
############################################

# Check for missing values on the columns
s=sapply(BeerMerge1,function(x) sum(is.na(x)))
gg_miss_var(BeerMerge1[,1:10]) + ylim(0,2500)
dim(BeerMerge1)

# There's missing values found on IBU and ABV columns of Beer data with 1005 missing values on IBU and 62 on ABV. This is a very high number which is approx half of the data. The total number of rows after the merge is 2410.

# We filterout the rows with missing values for the analysis
BeerMerge_Cleanup=BeerMerge1 %>% filter(!is.na(ABV),!is.na(IBU))

# Veify that all data is clean after cleanup. 
# The cleanup results in 1405 rows which will be used in our further case study.
s=sapply(BeerMerge_Cleanup,function(x) sum(is.na(x)))
dim(BeerMerge_Cleanup)
gg_miss_var(BeerMerge_Cleanup[,1:10]) + ylim(0,1500)


###################################################################################################
# 4. Compute the median alcohol content(ABV) and international bitterness unit(IBU) for each state. 
# Plot a bar chart to compare
###################################################################################################


# A. Finding the Median Alcohol content

MedAlco=BeerMerge_Cleanup %>% group_by(State) %>% summarize(Median_Alcohol_Content=median(ABV)) %>% arrange(Median_Alcohol_Content) 

MedAlco$State = factor(MedAlco$State,level=MedAlco$State[order(MedAlco$Median_Alcohol_Content)])

MedAlco %>% ggplot(aes(x=State,y=Median_Alcohol_Content)) + geom_bar (stat="identity") +ggtitle("Beer - Median Alcohol Content by State")


# B. Finding the Median bitterness 

MedBitter=BeerMerge_Cleanup %>% group_by(State) %>% summarize(Median_Bitter_Content=median(IBU)) %>% arrange(Median_Bitter_Content)

MedBitter$State = factor(MedBitter$State,level=MedBitter$State[order(MedBitter$Median_Bitter_Content)])

MedBitter %>% ggplot(aes(x=State,y=Median_Bitter_Content)) + geom_bar (stat="identity") +ggtitle("Beer - Median Bitter Content by State")


## The results from the above Median values for Alcohol Content and Bitterness were also arranged by state and plotted for the study.ABV has less variance than IBU variable.


###################################################################################################
# 5. Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer? 
###################################################################################################

#Find state with maximum ABV
BeerMerge_Cleanup %>% filter(ABV == max(ABV)) %>% select(State,ABV)
#Results from the above show Kentucky state has the Max alcohol content beer by 12.5%

#Find state with most bitter beer
BeerMerge_Cleanup %>% filter(IBU == max(IBU)) %>% select(State,IBU)
#Results from the above show Oregon state has the most bitter content beer by 138 unit


###########################################################################
# 6. Comment on the Summary statistics and distribution of ABV variable
###########################################################################


BeerSummary <- (summary(BeerMerge_Cleanup$ABV))

#> BeerSummary
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
# 0.02700 0.05000 0.05700 0.05991 0.06800 0.12500 

#From the summary statistics, it can be inferred that the ABV of our craft beers dataset follows a normal distribution because the median and the mean values are very close. There is a slight right skew to the data. Also from the Median  One thing to note is that 75% of all the beers have a 5% ABV or more. However, the interquartile distance is only 1.8% suggesting that 50% of the data is bounded between 5% and 6.8% ABV. It is also important to remember that missing values are not included in the summary statistics, and there's a possibility that this representation may not be accurate.


######################################################################################
#7. Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot.  Make your best judgment of a relationship and EXPLAIN your answer.
######################################################################################



#The scatterplot below provides visual evidence for a weak positive linear relationship between the alcohol content and the IBU values (R-Squared 0.44), meaning that 44% of the variation in the IBU of craft beers is explained by the Alcohol By Volume variable. This means that there are numerous other factors that may affect the IBU but are not accounted for in this linear regression.A simple way to define this relationship is that for every one percent increase in the ABV value, there is an increase of 12.2 units in the IBU average (pvalue < 0.001).
#There is a caveat to keep in mind for this regression analysis that 40% of the IBU data is missing. This could be strongly influencing the regression coefficients since currently there is no way of knowing exactly where that 40% falls within the overall spectrum of IBU values for all craft beers in the US. 

ggplot(BeerMerge_Cleanup,aes(x=ABV,y=IBU,colour=IBU)) + geom_point(shape=1) + geom_smooth(method=lm) + xlab("Alcohol by volume(ABV)") + ylab("Bitterness(IBU)") + ggtitle("Beer - Bitternes vs Alcohol Content") + scale_colour_gradientn(colours = rainbow(10))

